name: Deploy backend to Heroku environment

inputs:
  heroku-api-key:
    required: true
  heroku-email:
    required: true
  heroku-app-name:
    required: true
  mg-database-url:
    required: true
  firebase-web-api-key:
    required: true
  firebase-request-uri:
    required: true
  firebase-storage-default-bucket:
    required: true
  firebase-project-id:
    required: true
  firebase-svc-account-private-key:
    required: true
  firebase-svc-account-client-email:
    required: true
  mailer-user:
    required: true
  mailer-client-id:
    required: true
  mailer-client-secret:
    required: true
  mailer-refresh-token:
    required: true
  stripe-publishable-key:
    required: true
  stripe-secret-key:
    required: true

runs:
  using: "composite"
  steps:
    - name: Set Heroku login credentials
      run: |
        cat > ~/.netrc <<EOF
          machine api.heroku.com
            login $HEROKU_EMAIL
            password $HEROKU_API_KEY
          machine git.heroku.com
            login $HEROKU_EMAIL
            password $HEROKU_API_KEY
        EOF
      env:
        HEROKU_API_KEY: "${{ inputs.heroku-api-key }}"
        HEROKU_EMAIL: "${{ inputs.heroku-email }}"
    - name: Add Heroku git remote
      run: heroku git:remote --app $HEROKU_APP_NAME
      env:
        HEROKU_APP_NAME: "${{ inputs.heroku-app-name }}"
    - name: Set Heroku config vars
      run: |
        heroku config:set MG_DATABASE_URL="${{ inputs.mg-database-url }}" -a $HEROKU_APP_NAME && \
        heroku config:set FIREBASE_WEB_API_KEY="${{ inputs.firebase-web-api-key }}" -a $HEROKU_APP_NAME && \
        heroku config:set FIREBASE_REQUEST_URI="${{ inputs.firebase-request-uri }}" -a $HEROKU_APP_NAME && \
        heroku config:set FIREBASE_STORAGE_DEFAULT_BUCKET="${{ inputs.firebase-storage-default-bucket }}" -a $HEROKU_APP_NAME && \
        heroku config:set FIREBASE_PROJECT_ID="${{ inputs.firebase-project-id }}" -a $HEROKU_APP_NAME && \
        heroku config:set FIREBASE_SVC_ACCOUNT_PRIVATE_KEY="${{ inputs.firebase-svc-account-private-key }}" -a $HEROKU_APP_NAME && \
        heroku config:set FIREBASE_SVC_ACCOUNT_CLIENT_EMAIL="${{ inputs.firebase-svc-account-client-email }}" -a $HEROKU_APP_NAME && \
        heroku config:set MAILER_USER="${{ inputs.mailer-user }}" -a $HEROKU_APP_NAME && \
        heroku config:set MAILER_CLIENT_ID="${{ inputs.mailer-client-id }}" -a $HEROKU_APP_NAME && \
        heroku config:set MAILER_CLIENT_SECRET="${{ inputs.mailer-client-secret }}" -a $HEROKU_APP_NAME && \
        heroku config:set MAILER_REFRESH_TOKEN="${{ inputs.mailer-refresh-token }}" -a $HEROKU_APP_NAME && \
        heroku config:set STRIPE_PUBLISHABLE_TEST_KEY="${{ inputs.stripe-publishable-key }}" -a $HEROKU_APP_NAME && \
        heroku config:set STRIPE_SECRET_TEST_KEY="${{ inputs.stripe-secret-key }}" -a $HEROKU_APP_NAME && \
        heroku config:set PREVIEW_DEPLOY=true -a $HEROKU_APP_NAME
      env:
        HEROKU_APP_NAME: "${{ inputs.heroku-app-name }}"
    - name: Push to Heroku
      run: git subtree push --prefix backend/typescript heroku dev
