export type CampResponse = {
  id: string;
  active: boolean;
  ageLower: number;
  ageUpper: number;
  campCoordinators: string[];
  campCounsellors: string[];
  name: string;
  description: string;
  earlyDropoff: string;
  endTime: string;
  latePickup: string;
  location: string;
  startTime: string;
  fee: number;
  formQuestions: string[];
  campSessions: string[];
  fileName?: string;
  volunteers: string[];
};
