name: Deploy backend to Heroku dev environment

on:
  push:
    branches:
      - dev
    paths:
      - "backend/typescript/**"

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment: fon-staging
    steps:
      - name: Check out repository
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Deploy to Heroku
        uses: ./.github/actions/heroku-deploy
        with:
          heroku-api-key: "${{ secrets.HEROKU_API_KEY }}"
          heroku-email: "${{ secrets.HEROKU_EMAIL }}"
          heroku-app-name: "${{ secrets.HEROKU_APP_NAME }}"
          mg-database-url: "${{ secrets.MG_DATABASE_URL }}"
          firebase-web-api-key: "${{ secrets.FIREBASE_WEB_API_KEY }}"
          firebase-request-uri: "${{ secrets.FIREBASE_REQUEST_URI }}"
          firebase-storage-default-bucket: "${{ secrets.FIREBASE_STORAGE_DEFAULT_BUCKET }}"
          firebase-project-id: "${{ secrets.FIREBASE_PROJECT_ID }}"
          firebase-svc-account-private-key: "${{ secrets.FIREBASE_SVC_ACCOUNT_PRIVATE_KEY }}"
          firebase-svc-account-client-email: "${{ secrets.FIREBASE_SVC_ACCOUNT_CLIENT_EMAIL }}"
          mailer-user: "${{ secrets.MAILER_USER }}"
          mailer-client-id: "${{ secrets.MAILER_CLIENT_ID }}"
          mailer-client-secret: "${{ secrets.MAILER_CLIENT_SECRET }}"
          mailer-refresh-token: "${{ secrets.MAILER_REFRESH_TOKEN }}"
          stripe-publishable-key: "${{ secrets.STRIPE_PUBLISHABLE_TEST_KEY }}"
          stripe-secret-key: "${{ secrets.STRIPE_SECRET_TEST_KEY }}"
          deploy-branch: "dev"
